/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package departamentalizacionplanilla;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryan
 */
public class Concepto extends javax.swing.JFrame {
    public static int intCod=0;
    /**
     * Creates new form Concepto
     */
    //método para actualizar los combobox donde se hacen las búsquedas
    public void actualizarbusqueda(){
        //quita todos los items que tiene el combo
        cmbbusqueda.removeAllItems();
        cmbbusqueda.addItem("");
        try{
            //Conección con la base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select nombre_concepto from concepto");
            ResultSet rs = pst.executeQuery();
            
            boolean r=rs.next();
            //mientras encuentre datos en la tabla y campo especificado
            while(r){
                //se agrega lo encontrado al combo 
                cmbbusqueda.addItem(rs.getString("nombre_concepto"));
                r=rs.next();
            }
        }catch (Exception e){
            System.out.println("le dio un pujaso");
        }
    }
    //método para dejar en blanco los textbox y combobox
    public void limpiar(){
        txtcod.setText("");
        txtconcepto.setText("");
        cmbefecto.setSelectedIndex(0);
    }
    public Concepto() {
        try{
            //Conección con la base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from concepto");
            ResultSet rs = pst.executeQuery();
            boolean r=rs.next();
            //mientras encuentre datos en la tabla y campo especificado
            while(r){
                //intCod servirá para código automático por lo que se busca el más grande guardado en la base de datos
                if (intCod< Integer.parseInt(rs.getString("codigo_concepto"))) {
                    intCod=Integer.parseInt(rs.getString("codigo_concepto"));
                }
                r=rs.next();
            }
            intCod++;
            System.out.println(intCod);
        }catch (Exception e){
            System.out.println("le dio un pujaso");
        }
        initComponents();
        actualizarbusqueda();
        lblcodigo.setVisible(false);
        lblconcepto.setVisible(false);
        lblefecto.setVisible(false);
        txtcod.setVisible(false);
        cmbefecto.setVisible(false);
        txtconcepto.setVisible(false);
        btnaccion.setVisible(false);
        lblbusqueda.setVisible(false);
        cmbbusqueda.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblefecto = new javax.swing.JLabel();
        txtconcepto = new javax.swing.JTextField();
        lblconcepto = new javax.swing.JLabel();
        cmbefecto = new javax.swing.JComboBox<>();
        txtcod = new javax.swing.JTextField();
        lblcodigo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmboperacion = new javax.swing.JComboBox<>();
        btnaccion = new javax.swing.JButton();
        cmbbusqueda = new javax.swing.JComboBox<>();
        lblbusqueda = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONCEPTOS");
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblefecto.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblefecto.setText("Efecto");
        getContentPane().add(lblefecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txtconcepto.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtconcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 180, -1));

        lblconcepto.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblconcepto.setText("Concepto");
        getContentPane().add(lblconcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        cmbefecto.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cmbefecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "+", "-" }));
        cmbefecto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbefectoItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbefecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 80, -1));

        txtcod.setEditable(false);
        txtcod.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 84, -1));

        lblcodigo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblcodigo.setText("Código");
        getContentPane().add(lblcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Operación");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        cmboperacion.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cmboperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Agregar", "Modificar", "Eliminar" }));
        cmboperacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmboperacionItemStateChanged(evt);
            }
        });
        cmboperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboperacionActionPerformed(evt);
            }
        });
        getContentPane().add(cmboperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 140, -1));

        btnaccion.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnaccion.setText("jButton1");
        btnaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        cmbbusqueda.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cmbbusqueda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbusquedaItemStateChanged(evt);
            }
        });
        cmbbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 180, -1));

        lblbusqueda.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblbusqueda.setText("Concepto");
        getContentPane().add(lblbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbefectoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbefectoItemStateChanged
        
    }//GEN-LAST:event_cmbefectoItemStateChanged

    private void cmboperacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmboperacionItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboperacionItemStateChanged

    private void cmboperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboperacionActionPerformed
        // TODO add your handling code here:
        //se oculta lo innecesario, se muestra lo necesario y se cambia el texto al botón
        if (cmboperacion.getSelectedIndex()==1) {
            limpiar();
            lblcodigo.setVisible(false);
            lblconcepto.setVisible(true);
            lblefecto.setVisible(true);
            txtcod.setVisible(false);
            cmbefecto.setVisible(true);
            txtconcepto.setVisible(true);
            btnaccion.setVisible(true);
            lblbusqueda.setVisible(false);
            cmbbusqueda.setVisible(false);
            btnaccion.setText("Agregar");
            //se oculta lo innecesario, se muestra lo necesario y se cambia el texto al botón
        }else if (cmboperacion.getSelectedIndex()==2) {
            limpiar();
            lblcodigo.setVisible(true);
            lblconcepto.setVisible(true);
            lblefecto.setVisible(true);
            txtcod.setVisible(true);
            cmbefecto.setVisible(true);
            txtconcepto.setVisible(true);
            btnaccion.setVisible(false);
            lblbusqueda.setVisible(true);
            cmbbusqueda.setVisible(true);
            btnaccion.setText("Modificar");
            //se oculta lo innecesario, se muestra lo necesario y se cambia el texto al botón
        }else if (cmboperacion.getSelectedIndex()==3) {
            limpiar();
            lblcodigo.setVisible(true);
            lblconcepto.setVisible(true);
            lblefecto.setVisible(true);
            txtcod.setVisible(true);
            cmbefecto.setVisible(true);
            txtconcepto.setVisible(true);
            btnaccion.setVisible(false);
            lblbusqueda.setVisible(true);
            cmbbusqueda.setVisible(true);
            btnaccion.setText("Eliminar");
            //se oculta lo innecesario, se muestra lo necesario y se cambia el texto al botón
        }else{
            limpiar();
            lblcodigo.setVisible(false);
            lblconcepto.setVisible(false);
            lblefecto.setVisible(false);
            txtcod.setVisible(false);
            cmbefecto.setVisible(false);
            txtconcepto.setVisible(false);
            btnaccion.setVisible(false);
            lblbusqueda.setVisible(false);
            cmbbusqueda.setVisible(false);
        }
    }//GEN-LAST:event_cmboperacionActionPerformed

    private void btnaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccionActionPerformed
        // TODO add your handling code here:
        //se verifica que todo este ingresado y también esté ingresado correctamente
        if (cmboperacion.getSelectedIndex()==1) {
            if (txtconcepto.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Debe de ingresar el nombre del concepto");
            }else if (cmbefecto.getSelectedIndex()==0) {
                JOptionPane.showMessageDialog(this, "Debe de seleccionar el efecto del concepto");
            }else{
                try{
                    //Conección con la base de datos
                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                    PreparedStatement pst = cn.prepareStatement("insert into concepto values(?,?,?)");

                    pst.setString(1, String.valueOf(intCod));
                    pst.setString(2, txtconcepto.getText().trim());
                    pst.setString(3, String.valueOf(cmbefecto.getSelectedItem()));
                    pst.executeUpdate();
                    intCod++;
                    //se agregan los datos ingresados a la base de datos 
                    JOptionPane.showMessageDialog(this, "Datos ingresados correctamente","ÉXITO",JOptionPane.INFORMATION_MESSAGE);
                    //se llama el método de limpiar para dejar en blanco todo
                    limpiar();
                    //se llama el método para actualizar los combobox
                    actualizarbusqueda();
                }catch (Exception e){
                   System.out.println("le dio un error");
                }
            }
        }else if (cmboperacion.getSelectedIndex()==2) {
            if (JOptionPane.showConfirmDialog(this, "Está seguro de modificar los datos?","MODIFICAR",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
               try {
                    String ID = txtcod.getText().trim();
                    //Conección con la base de datos
                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                    PreparedStatement pst = cn.prepareStatement("update concepto set nombre_concepto= ?, efecto_concepto = ? where codigo_concepto= " + ID);

                    pst.setString(1, txtconcepto.getText().trim());
                    pst.setString(2, cmbefecto.getSelectedItem().toString());
                    pst.executeUpdate();
                    //se modifican los datos especificados en la base de datos 
                    JOptionPane.showMessageDialog(this, "Datos modificados correctamente","ÉXITO",JOptionPane.INFORMATION_MESSAGE);
                    //se llama el método de limpiar para dejar en blanco todo
                    limpiar();
                    //se llama el método para actualizar los combobox
                    actualizarbusqueda();
                } catch (Exception e) {
                    System.out.println("le dio un pujaso");
                } 
            }
        }else if (cmboperacion.getSelectedIndex()==3) {
            if (JOptionPane.showConfirmDialog(this, "Está seguro de eliminar los datos?","MODIFICAR",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
               try {
                    String ID = txtcod.getText().trim();
                    //Conección con la base de datos
                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                    PreparedStatement pst = cn.prepareStatement("delete from concepto where codigo_concepto= " + ID);

                    pst.executeUpdate();
                    //se eliminan los datos especificados en la base de datos 
                    JOptionPane.showMessageDialog(this, "Datos eliminados correctamente","ÉXITO",JOptionPane.INFORMATION_MESSAGE);
                    //se llama el método de limpiar para dejar en blanco todo
                    limpiar();
                    //se llama el método para actualizar los combobox
                    actualizarbusqueda();
                } catch (Exception e) {
                    System.out.println("le dio un pujaso");
                } 
            }
        }
    }//GEN-LAST:event_btnaccionActionPerformed

    private void cmbbusquedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbusquedaItemStateChanged
        // TODO add your handling code here:
        //sirve para la búsqueda
        if (cmbbusqueda.getSelectedIndex()!=0) {
            try{
                //Conección con la base de datos
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                PreparedStatement pst = cn.prepareStatement("select * from concepto where nombre_concepto = ?");
                pst.setString(1,cmbbusqueda.getSelectedItem().toString());
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    //si encuentra lo especificado se muestran los valores obtenidos en pantalla
                    txtcod.setText(rs.getString("codigo_concepto"));
                    txtconcepto.setText(rs.getString("nombre_concepto"));
                    cmbefecto.setSelectedItem(rs.getString("efecto_concepto"));
                    btnaccion.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "No encontrado");
                }

            }catch (Exception e){
                //System.out.println("le dio un pujaso");
            }
        }else{
            //se llama el método de limpiar para dejar en blanco todo
            limpiar();
            btnaccion.setVisible(false);
        }
    }//GEN-LAST:event_cmbbusquedaItemStateChanged

    private void cmbbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbusquedaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbbusquedaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menú inf=new Menú();
                this.dispose();
                inf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Concepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Concepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Concepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Concepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Concepto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaccion;
    private javax.swing.JComboBox<String> cmbbusqueda;
    private javax.swing.JComboBox<String> cmbefecto;
    private javax.swing.JComboBox<String> cmboperacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblbusqueda;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblconcepto;
    private javax.swing.JLabel lblefecto;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtconcepto;
    // End of variables declaration//GEN-END:variables
}
