/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package departamentalizacionplanilla;

import static departamentalizacionplanilla.Empleados.intCod;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javafx.scene.control.DatePicker;
import javafx.util.converter.LocalDateStringConverter;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryan
 */
public class Nomina extends javax.swing.JFrame {
    
    /**
     * Creates new form Nomina
     */
    public static int intCod=0;
    //método para tener los dias con 2 dígitos
    public static String strDia(int intdia){
        String strDia="";
        //si el dia es menor o igual a 9 se agrega un 0 antes
        if (intdia<=9) {
            strDia="0"+String.valueOf(intdia);
        }else{
            strDia=String.valueOf(intdia);
        }
        return strDia;
    }
    //método para tener los meses con 2 dígitos
    public static String strMes(int intmes){
        String strMes="";
        //si el mes es menor o igual a 9 se agrega un 0 antes
        if (intmes<9) {
            strMes="0"+String.valueOf(intmes+1);
        }else{
            strMes=String.valueOf(intmes+1);
        }
        return strMes;
    }
    //se toman solo las letras del subindice 1 al 3 del texto obtenido
    public static String strA(int intA){
        String strA=String.valueOf(intA).substring(1, 3);
        return strA;
    }
    public void limpiar(){
        txtcod.setText("");
    }
    //método para actualizar los combobox donde se hacen las búsquedas
    public void actualizarbusqueda(){
        //quita todos los items que tiene el combo
        cmbbusqueda.removeAllItems();
        cmbbusqueda.addItem("");
        try{
            //Conección con la base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from nomina_encabezado");
            ResultSet rs = pst.executeQuery();
            
            boolean r=rs.next();
            //mientras encuentre datos en la tabla y campo especificado
            while(r){
                //se agrega lo encontrado al combo 
                cmbbusqueda.addItem(rs.getString("fecha_inicial_nominal")+" - "+rs.getString("fecha_final_nominal"));
                r=rs.next();
            }
        }catch (Exception e){
            System.out.println("le dio un pujaso");
        }
    }
    public Nomina() {
        try{
            //Conección con la base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from nomina_encabezado");
            ResultSet rs = pst.executeQuery();
            
            boolean r=rs.next();
            //mientras encuentre datos en la tabla y campo especificado
            while(r){
                //intCod servirá para código automático por lo que se busca el más grande guardado en la base de datos
                if (intCod< Integer.parseInt(rs.getString("codigo_nominal"))) {
                    intCod=Integer.parseInt(rs.getString("codigo_nominal"));
                }
                r=rs.next();
            }
            intCod++;
            System.out.println(intCod);
        }catch (Exception e){
            System.out.println("le dio un pujaso");
        }
        initComponents();
        //se llama el método para actualizar los combobox
        actualizarbusqueda();
        lblbusqueda.setVisible(false);
        cmbbusqueda.setVisible(false);
        lblcodigo.setVisible(false);
        txtcod.setVisible(false);
        lblfi.setVisible(false);
        lblff.setVisible(false);
        dtpfi.setVisible(false);
        dtpff.setVisible(false);
        btnaccion.setVisible(false);
        
        dtpff.setFormats("dd/MM/yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtpfi = new org.jdesktop.swingx.JXDatePicker();
        dtpff = new org.jdesktop.swingx.JXDatePicker();
        cmboperacion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lblbusqueda = new javax.swing.JLabel();
        cmbbusqueda = new javax.swing.JComboBox<>();
        lblfi = new javax.swing.JLabel();
        lblff = new javax.swing.JLabel();
        btnaccion = new javax.swing.JButton();
        lblcodigo = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NOMINA");
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dtpfi.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        dtpfi.setFormats("dd/MM/yyyy");
        dtpfi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtpfiMouseClicked(evt);
            }
        });
        dtpfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtpfiActionPerformed(evt);
            }
        });
        getContentPane().add(dtpfi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        dtpff.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(dtpff, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        cmboperacion.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cmboperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Agregar", "Modificar" }));
        cmboperacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmboperacionItemStateChanged(evt);
            }
        });
        cmboperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboperacionActionPerformed(evt);
            }
        });
        getContentPane().add(cmboperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 115, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Operación");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        lblbusqueda.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblbusqueda.setText("Fecha de Nomina");
        getContentPane().add(lblbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        cmbbusqueda.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cmbbusqueda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbusquedaItemStateChanged(evt);
            }
        });
        cmbbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 220, -1));

        lblfi.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblfi.setText("Fecha Inicial");
        getContentPane().add(lblfi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        lblff.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblff.setText("Fecha Final");
        getContentPane().add(lblff, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        btnaccion.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnaccion.setText("jButton1");
        btnaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        lblcodigo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblcodigo.setText("Código");
        getContentPane().add(lblcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        txtcod.setEditable(false);
        txtcod.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 84, -1));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmboperacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmboperacionItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboperacionItemStateChanged

    private void cmboperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboperacionActionPerformed
        // TODO add your handling code here:
        //se oculta lo innecesario, se muestra lo necesario y se cambia el texto al botón
        if (cmboperacion.getSelectedIndex()==1) {
            limpiar();
            lblbusqueda.setVisible(false);
            cmbbusqueda.setVisible(false);
            lblcodigo.setVisible(false);
            txtcod.setVisible(false);
            lblfi.setVisible(true);
            lblff.setVisible(true);
            dtpfi.setVisible(true);
            dtpff.setVisible(true);
            btnaccion.setVisible(true);
            btnaccion.setText("Agregar");
            //se oculta lo innecesario, se muestra lo necesario y se cambia el texto al botón
        }else if (cmboperacion.getSelectedIndex()==2) {
            limpiar();
            lblbusqueda.setVisible(true);
            cmbbusqueda.setVisible(true);
            lblcodigo.setVisible(true);
            txtcod.setVisible(true);
            lblfi.setVisible(true);
            lblff.setVisible(true);
            dtpfi.setVisible(true);
            dtpff.setVisible(true);
            btnaccion.setVisible(false);
            btnaccion.setText("Modificar");
            //se oculta lo innecesario, se muestra lo necesario y se cambia el texto al botón
        }else{
            limpiar();
            lblbusqueda.setVisible(false);
            cmbbusqueda.setVisible(false);
            lblcodigo.setVisible(false);
            txtcod.setVisible(false);
            lblfi.setVisible(false);
            lblff.setVisible(false);
            dtpfi.setVisible(false);
            dtpff.setVisible(false);
        }
    }//GEN-LAST:event_cmboperacionActionPerformed

    private void cmbbusquedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbusquedaItemStateChanged
        // TODO add your handling code here:
        //sirve para la búsqueda
        String strTexto;
        //dar formato a la fecha
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
        if (cmbbusqueda.getSelectedIndex()!=0) {
            try{
                //Conección con la base de datos
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                PreparedStatement pst = cn.prepareStatement("select * from nomina_encabezado where fecha_inicial_nominal = ?");
                pst.setString(1,cmbbusqueda.getSelectedItem().toString().substring(0, 8));
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    //si encuentra lo especificado se muestran los valores obtenidos en pantalla
                    txtcod.setText(rs.getString("codigo_nominal"));
                    strTexto=rs.getString("fecha_inicial_nominal");
                    dtpfi.setDate(formatoDelTexto.parse(strTexto));
                    strTexto=rs.getString("fecha_final_nominal");
                    dtpff.setDate(formatoDelTexto.parse(strTexto));
                    btnaccion.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "No encontrado");
                }

            }catch (Exception e){
                //System.out.println("le dio un pujaso");
            }
        }else{
            //se llama el método de limpiar para dejar en blanco todo
            limpiar();
            if (cmboperacion.getSelectedIndex()!=1) {
                btnaccion.setVisible(false);
            }

        }
    }//GEN-LAST:event_cmbbusquedaItemStateChanged

    private void cmbbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbusquedaActionPerformed

    private void btnaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccionActionPerformed
        // TODO add your handling code here:
        //se verifica que todo este ingresado y también esté ingresado correctamente
        if (cmboperacion.getSelectedIndex()==1) {
            if (dtpfi.getDate().equals("")) {
                JOptionPane.showMessageDialog(this, "Debe de seleccionar la fecha inicial de la nomina");
            }else if (dtpff.getDate().equals("")) {
                JOptionPane.showMessageDialog(this, "Debe de seleccionar la fecha final de la nomina");
            }else{
                try{
                    //Conección con la base de datos
                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                    PreparedStatement pst = cn.prepareStatement("insert into nomina_encabezado values(?,?,?,?)");
                    pst.setString(1, String.valueOf(intCod));
                    pst.setString(2, String.valueOf(strDia(dtpfi.getDate().getDate()))+"/"+String.valueOf(strMes(dtpfi.getDate().getMonth()))+"/"+String.valueOf(strA(dtpfi.getDate().getYear())));
                    pst.setString(3, String.valueOf(strDia(dtpff.getDate().getDate()))+"/"+String.valueOf(strMes(dtpff.getDate().getMonth()))+"/"+String.valueOf(strA(dtpff.getDate().getYear())));
                    pst.setString(4, "0");
                    pst.executeUpdate();
                    intCod++;
                    //se agregan los datos ingresados a la base de datos 
                    JOptionPane.showMessageDialog(this, "Datos ingresados correctamente","ÉXITO",JOptionPane.INFORMATION_MESSAGE);
                    //se llama el método de limpiar para dejar en blanco todo
                    limpiar();
                    //se llama el método para actualizar los combobox
                    actualizarbusqueda();
                }catch (Exception e){
                    System.out.println("le dio un error");
                }
            }
        }else if (cmboperacion.getSelectedIndex()==2) {
            if (JOptionPane.showConfirmDialog(this, "Está seguro de modificar los datos?","MODIFICAR",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
                try {
                    String ID = txtcod.getText().trim();
                    //Conección con la base de datos
                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                    PreparedStatement pst = cn.prepareStatement("update nomina_encabezado set fecha_inicial_nominal= ?, fecha_final_nominal= ? where codigo_nominal= " + ID);

                    pst.setString(1, String.valueOf(strDia(dtpfi.getDate().getDate()))+"/"+String.valueOf(strMes(dtpfi.getDate().getMonth()))+"/"+String.valueOf(strA(dtpfi.getDate().getYear())));
                    pst.setString(2, String.valueOf(strDia(dtpff.getDate().getDate()))+"/"+String.valueOf(strMes(dtpff.getDate().getMonth()))+"/"+String.valueOf(strA(dtpff.getDate().getYear())));
                    pst.executeUpdate();
                    //se modifican los datos especificados en la base de datos 
                    JOptionPane.showMessageDialog(this, "Datos modificados correctamente","ÉXITO",JOptionPane.INFORMATION_MESSAGE);
                    //se llama el método de limpiar para dejar en blanco todo
                    limpiar();
                    //se llama el método para actualizar los combobox
                    actualizarbusqueda();
                } catch (Exception e) {
                    System.out.println("le dio un pujaso de modificacion");
                }
            }
        }
    }//GEN-LAST:event_btnaccionActionPerformed

    private void dtpfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtpfiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtpfiActionPerformed

    private void dtpfiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtpfiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dtpfiMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menú inf=new Menú();
        this.dispose();
        inf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaccion;
    private javax.swing.JComboBox<String> cmbbusqueda;
    private javax.swing.JComboBox<String> cmboperacion;
    private org.jdesktop.swingx.JXDatePicker dtpff;
    private org.jdesktop.swingx.JXDatePicker dtpfi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblbusqueda;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblff;
    private javax.swing.JLabel lblfi;
    private javax.swing.JTextField txtcod;
    // End of variables declaration//GEN-END:variables
}
