/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package departamentalizacionplanilla;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *Bryan Orlando Aguirre Sagastume
*0901-17-646
*Planilla para calcular el sueldo líquido de trabajadores y obtener los totales devengados por departamento 
 * @author Bryan
 */
public class Planilla extends javax.swing.JFrame {
    public static int intFilas,intConcepto;
    public static double dblTotal;
    /**
     * Creates new form Planilla
     */
    public Planilla() {
        initComponents();
        intConcepto=0;
        cmbcodfn.setVisible(false);
        cmbfn.addItem("");
        cmbcodfn.addItem("");
        try{
            //Conección con la base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from nomina_encabezado");
            ResultSet rs = pst.executeQuery();
            //mientras encuentre datos en la tabla y campo especificado
            boolean r=rs.next();
            while(r){
                //se agrega lo encontrado al combo 
                cmbfn.addItem(rs.getString("fecha_inicial_nominal")+" - "+rs.getString("fecha_final_nominal"));
                cmbcodfn.addItem(rs.getString("codigo_nominal"));
                r=rs.next();
            }
        }catch (Exception e){
            System.out.println("le dio un pujaso");
        }
        DefaultTableModel dtm= (DefaultTableModel) dgvtabla.getModel();
        try{
            //Conección con la base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from concepto");
            ResultSet rs = pst.executeQuery();
            
            boolean r=rs.next();
            //mientras encuentre datos en la tabla y campo especificado
            while(r){
                //se agrega columna a la tabla por cada concepto encontrado 
                dtm.addColumn(rs.getString("nombre_concepto"));
                intConcepto++;
                r=rs.next();
            }
        }catch (Exception e){
            System.out.println("le dio un pujaso");
        }
        dtm.addColumn("Sueldo Liquido");
        dtm.addColumn("Departamento");
        dgvtabla.setModel(dtm);
        DefaultTableModel dtmdep= (DefaultTableModel) dgvdep.getModel();
        try{
            //Conección con la base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from departamentos");
            ResultSet rs = pst.executeQuery();
            
            boolean r=rs.next();
            //se agrega columna a la tabla por cada Departamento encontrado 
            while(r){
                Object [] filaDep={rs.getString("nombre_depto")};
                dtmdep.addRow(filaDep);
                r=rs.next();
            }
        }catch (Exception e){
            System.out.println("le dio un pujaso");
        }
        for (int i = dgvdep.getModel().getRowCount()-1; i>=0; i--) {
                dgvdep.getModel().setValueAt(0.00, i, 1);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dgvtabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        dgvdep = new javax.swing.JTable();
        cmbfn = new javax.swing.JComboBox<>();
        cmbcodfn = new javax.swing.JComboBox<>();
        lblfecha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PLANILLA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dgvtabla.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        dgvtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane1.setViewportView(dgvtabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1020, 300));

        jTable2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"2600-5000", "3"},
                {"5001-10000", "5"},
                {"10001-100000", "10"}
            },
            new String [] {
                "Intervalo de sueldo", "% ISR"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, 280, 80));

        dgvdep.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        dgvdep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Departamento", "Totales"
            }
        ));
        jScrollPane3.setViewportView(dgvdep);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 210, 300, 200));

        cmbfn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cmbfn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbfnItemStateChanged(evt);
            }
        });
        cmbfn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbfnActionPerformed(evt);
            }
        });
        getContentPane().add(cmbfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 260, -1));

        cmbcodfn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cmbcodfn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbcodfnItemStateChanged(evt);
            }
        });
        cmbcodfn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcodfnActionPerformed(evt);
            }
        });
        getContentPane().add(cmbcodfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 115, -1));

        lblfecha.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblfecha.setText("Fecha Nomina");
        getContentPane().add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbfnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbfnItemStateChanged

    }//GEN-LAST:event_cmbfnItemStateChanged

    private void cmbfnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbfnActionPerformed
        // TODO add your handling code here:
        for (int i = dgvdep.getModel().getRowCount()-1; i>=0; i--) {
                dgvdep.getModel().setValueAt(0.00, i, 1);
        }
        DefaultTableModel dtmnomina= (DefaultTableModel) dgvtabla.getModel();
        int intFila=-1, intColumna=1, intEcontrado=0;
        try{
             for (int i = intFilas-1; i>=0; i--) {
                dtmnomina.removeRow(i);
            }
        }catch(Exception e){
            
        }
       
        
        String strCodant="";
        try{
            this.cmbcodfn.setSelectedIndex(this.cmbfn.getSelectedIndex());
        }catch(Exception e){
            
        }
        if (cmbfn.getSelectedIndex()!=0) {
            
           try{
               //Conección con la base de datos
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                PreparedStatement pst = cn.prepareStatement("select empleados.codigo_depto, empleados.codigo_emp, empleados.nombre_emp, nomina_detalle.codigo_nominal, nomina_detalle.codigo_emp,nomina_encabezado.codigo_nominal,nomina_detalle.codigo_nominal, departamentos.nombre_depto from empleados,nomina_detalle, nomina_encabezado, departamentos where empleados.codigo_depto=departamentos.codigo_depto and empleados.codigo_emp=nomina_detalle.codigo_emp and nomina_detalle.codigo_nominal=nomina_encabezado.codigo_nominal and nomina_encabezado.codigo_nominal="+String.valueOf(cmbcodfn.getSelectedItem()));
                ResultSet rs = pst.executeQuery();

                boolean r=rs.next();
                while(r){
                    if (!rs.getString("codigo_emp").equals(strCodant)) {
                        dblTotal=0;
                        intFila++;
                        Object [] filaDep={rs.getString("empleados.nombre_emp")};
                        dtmnomina.addRow(filaDep);
                        for (int i = 1; i <= intConcepto; i++) {
                            try{
                                intEcontrado=0;
                                //Conección con la base de datos
                                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                                PreparedStatement post = con.prepareStatement("SELECT * FROM nomina_detalle,concepto where nomina_detalle.codigo_concepto=concepto.codigo_concepto and nomina_detalle.codigo_nominal="+String.valueOf(cmbcodfn.getSelectedItem())+" and nomina_detalle.codigo_emp="+rs.getString("empleados.codigo_emp")+" and nomina_detalle.codigo_concepto="+ String.valueOf(i));
                                ResultSet ress = post.executeQuery();
                                boolean ra=ress.next();
                                while(ra){
                                    dgvtabla.getModel().setValueAt(ress.getString("nomina_detalle.valor_nominadetalle"), intFila, intColumna);
                                    if (ress.getString("concepto.efecto_concepto").equals("+")) {
                                        dblTotal+=Double.parseDouble(ress.getString("nomina_detalle.valor_nominadetalle"));
                                    }else{
                                        dblTotal-=Double.parseDouble(ress.getString("nomina_detalle.valor_nominadetalle"));
                                    }
                                    intColumna++;
                                    intEcontrado=1;
                                    ra=ress.next();
                                }
                                if (intEcontrado!=1) {
                                    dgvtabla.getModel().setValueAt("N.I.", intFila, intColumna);
                                    intColumna++;
                                }
                            }catch (Exception e){
                                System.out.println(e);
                            }
                        }
                        dgvtabla.getModel().setValueAt(dblTotal, intFila, intColumna);
                        intColumna++;
                        dgvtabla.getModel().setValueAt(rs.getString("departamentos.nombre_depto"), intFila, intColumna);
                        int intTotdep=Integer.parseInt(rs.getString("empleados.codigo_depto"));
                        Double dbltot=(Double) dgvdep.getValueAt(intTotdep-1, 1);
                        if (dbltot==null) {
                            dbltot=0.0;
                        }
                        dgvdep.getModel().setValueAt(dblTotal+dbltot, Integer.parseInt(rs.getString("empleados.codigo_depto"))-1, 1);
                    }
                    strCodant=rs.getString("empleados.codigo_emp");
                    intColumna=1;
                    r=rs.next();
                }
            }catch (Exception e){
                System.out.println("le dio un pujaso "+e);
            }
        }
        intFilas=dgvtabla.getModel().getRowCount();
    }//GEN-LAST:event_cmbfnActionPerformed

    private void cmbcodfnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbcodfnItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbcodfnItemStateChanged

    private void cmbcodfnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcodfnActionPerformed
        // TODO add your handling code here:
        try{
            this.cmbfn.setSelectedIndex(this.cmbcodfn.getSelectedIndex());
        }catch(Exception e){
        }
    }//GEN-LAST:event_cmbcodfnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menú inf=new Menú();
        this.dispose();
        inf.setVisible(true);
        /*for (int i = dgvtabla.getColumnCount()-1; i >= 1; i--) {
            dgvtabla.removeColumn(dgvtabla.getColumnModel().getColumn(i));
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbcodfn;
    private javax.swing.JComboBox<String> cmbfn;
    private javax.swing.JTable dgvdep;
    private javax.swing.JTable dgvtabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblfecha;
    // End of variables declaration//GEN-END:variables
}
