/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package departamentalizacionplanilla;

import static departamentalizacionplanilla.Concepto.intCod;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryan
 */
public class Puesto extends javax.swing.JFrame {
    public static int intCod=0;
    public void limpiar(){
        txtcod.setText("");
        txtpuesto.setText("");
    }
    public void actualizarbusqueda(){
        cmbbusqueda.removeAllItems();
        cmbbusqueda.addItem("");
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select nombre_puesto from puestos");
            ResultSet rs = pst.executeQuery();
            
            boolean r=rs.next();
            while(r){
                cmbbusqueda.addItem(rs.getString("nombre_puesto"));
                r=rs.next();
            }
        }catch (Exception e){
            System.out.println("le dio un pujaso");
        }
    }
    /**
     * Creates new form Ingreso_Puesto
     */
    public Puesto() {
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from puestos");
            ResultSet rs = pst.executeQuery();
            
            boolean r=rs.next();
            while(r){
                if (intCod< Integer.parseInt(rs.getString("codigo_puesto"))) {
                    intCod=Integer.parseInt(rs.getString("codigo_puesto"));
                }
                r=rs.next();
            }
            intCod++;
            System.out.println(intCod);
        }catch (Exception e){
            System.out.println("le dio un pujaso");
        }
        initComponents();
        actualizarbusqueda();
        lblcodigo.setVisible(false);
        lblpuesto.setVisible(false);
        txtcod.setVisible(false);
        txtpuesto.setVisible(false);
        btnaccion.setVisible(false);
        lblbusqueda.setVisible(false);
        cmbbusqueda.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        cmboperacion = new javax.swing.JComboBox<>();
        lblcodigo = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        lblbusqueda = new javax.swing.JLabel();
        cmbbusqueda = new javax.swing.JComboBox<>();
        lblpuesto = new javax.swing.JLabel();
        txtpuesto = new javax.swing.JTextField();
        btnaccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Operación");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        cmboperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Agregar", "Modificar", "Eliminar" }));
        cmboperacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmboperacionItemStateChanged(evt);
            }
        });
        cmboperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboperacionActionPerformed(evt);
            }
        });
        getContentPane().add(cmboperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 115, -1));

        lblcodigo.setText("Código");
        getContentPane().add(lblcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        txtcod.setEditable(false);
        getContentPane().add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 84, -1));

        lblbusqueda.setText("Puesto");
        getContentPane().add(lblbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        cmbbusqueda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbusquedaItemStateChanged(evt);
            }
        });
        cmbbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 115, -1));

        lblpuesto.setText("Puesto");
        getContentPane().add(lblpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));
        getContentPane().add(txtpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 84, -1));

        btnaccion.setText("jButton1");
        btnaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmboperacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmboperacionItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboperacionItemStateChanged

    private void cmboperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboperacionActionPerformed
        // TODO add your handling code here:
        if (cmboperacion.getSelectedIndex()==1) {
            limpiar();
            lblcodigo.setVisible(false);
            lblpuesto.setVisible(true);
            txtcod.setVisible(false);
            txtpuesto.setVisible(true);
            btnaccion.setVisible(true);
            lblbusqueda.setVisible(false);
            cmbbusqueda.setVisible(false);
            btnaccion.setText("Agregar");
        }else if (cmboperacion.getSelectedIndex()==2) {
            limpiar();
            lblcodigo.setVisible(true);
            lblpuesto.setVisible(true);
            txtcod.setVisible(true);
            txtpuesto.setVisible(true);
            btnaccion.setVisible(false);
            lblbusqueda.setVisible(true);
            cmbbusqueda.setVisible(true);
            btnaccion.setText("Modificar");
        }else if (cmboperacion.getSelectedIndex()==3) {
            limpiar();
            lblcodigo.setVisible(true);
            lblpuesto.setVisible(true);
            txtcod.setVisible(true);
            txtpuesto.setVisible(true);
            btnaccion.setVisible(false);
            lblbusqueda.setVisible(true);
            cmbbusqueda.setVisible(true);
            btnaccion.setText("Eliminar");
        }else{
            limpiar();
            lblcodigo.setVisible(false);
            lblpuesto.setVisible(false);
            txtcod.setVisible(false);
            txtpuesto.setVisible(false);
            btnaccion.setVisible(false);
            lblbusqueda.setVisible(false);
            cmbbusqueda.setVisible(false);
        }
    }//GEN-LAST:event_cmboperacionActionPerformed

    private void cmbbusquedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbusquedaItemStateChanged
        // TODO add your handling code here:
        if (cmbbusqueda.getSelectedIndex()!=0) {
            try{
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                PreparedStatement pst = cn.prepareStatement("select * from puestos where nombre_puesto = ?");
                pst.setString(1,cmbbusqueda.getSelectedItem().toString());
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    txtcod.setText(rs.getString("codigo_puesto"));
                    txtpuesto.setText(rs.getString("nombre_puesto"));
                    btnaccion.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "No encontrado");
                }

            }catch (Exception e){
                //System.out.println("error al agregar al de busqueda");
            }
        }else{
            limpiar();
            if (cmboperacion.getSelectedIndex()!=1) {
                btnaccion.setVisible(false);
            }
        }
    }//GEN-LAST:event_cmbbusquedaItemStateChanged

    private void cmbbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbusquedaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbbusquedaActionPerformed

    private void btnaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccionActionPerformed
        // TODO add your handling code here:
        if (cmboperacion.getSelectedIndex()==1) {
            if (txtpuesto.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Debe de ingresar el nombre del puesto");
            }else{
                try{
                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                    PreparedStatement pst = cn.prepareStatement("insert into puestos values(?,?)");

                    pst.setString(1, String.valueOf(intCod));
                    pst.setString(2, txtpuesto.getText().trim());
                    pst.executeUpdate();
                    intCod++;
                    JOptionPane.showMessageDialog(this, "Datos ingresados correctamente","ÉXITO",JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                    actualizarbusqueda();
                }catch (Exception e){
                    System.out.println("error al guardar");
                }
            }
        }else if (cmboperacion.getSelectedIndex()==2) {
            if (JOptionPane.showConfirmDialog(this, "Está seguro de modificar los datos?","MODIFICAR",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
                try {
                    String ID = txtcod.getText().trim();

                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                    PreparedStatement pst = cn.prepareStatement("update puestos set nombre_puesto= ? where codigo_puesto= " + ID);

                    pst.setString(1, txtpuesto.getText().trim());
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Datos modificados correctamente","ÉXITO",JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                    actualizarbusqueda();
                } catch (Exception e) {
                    System.out.println("error al modificar");
                }
            }
        }else if (cmboperacion.getSelectedIndex()==3) {
            if (JOptionPane.showConfirmDialog(this, "Está seguro de eliminar los datos?","MODIFICAR",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
                try {
                    String ID = txtcod.getText().trim();

                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                    PreparedStatement pst = cn.prepareStatement("delete from puestos where codigo_puesto= " + ID);

                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Datos eliminados correctamente","ÉXITO",JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                    actualizarbusqueda();
                } catch (Exception e) {
                    System.out.println("error al eliminar");
                }
            }
        }
    }//GEN-LAST:event_btnaccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaccion;
    private javax.swing.JComboBox<String> cmbbusqueda;
    private javax.swing.JComboBox<String> cmboperacion;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblbusqueda;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblpuesto;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtpuesto;
    // End of variables declaration//GEN-END:variables
}
