/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package departamentalizacionplanilla;

import static departamentalizacionplanilla.Departamento.intCod;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryan
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios
     */
    public static int intCod=0;
    public void limpiar(){
        txtcod.setText("");
        txtusuario.setText("");
        txtclave.setText("");
        cmbestado.setSelectedIndex(0);
        cmbemp.setSelectedIndex(0);
    }
    public void actualizarbusqueda(){
        cmbbusqueda.removeAllItems();
        cmbbusqueda.addItem("");
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select nombre_usuario from usuarios");
            ResultSet rs = pst.executeQuery();
            
            boolean r=rs.next();
            while(r){
                cmbbusqueda.addItem(rs.getString("nombre_usuario"));
                r=rs.next();
            }
        }catch (Exception e){
            System.out.println("le dio un pujaso");
        }
    }
    public Usuarios() {
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from usuarios");
            ResultSet rs = pst.executeQuery();
            
            boolean r=rs.next();
            while(r){
                if (intCod< Integer.parseInt(rs.getString("codigo_usuario"))) {
                    intCod=Integer.parseInt(rs.getString("codigo_usuario"));
                }
                r=rs.next();
            }
            intCod++;
            System.out.println(intCod);
        }catch (Exception e){
            System.out.println("le dio un pujaso");
        }
        initComponents();
        cmbemp.addItem("");
        cmbcodemp.addItem("");
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from empleados");
            ResultSet rs = pst.executeQuery();
            
            boolean r=rs.next();
            while(r){
                cmbemp.addItem(rs.getString("nombre_emp"));
                cmbcodemp.addItem(rs.getString("codigo_emp"));
                r=rs.next();
            }
        }catch (Exception e){
            System.out.println("le dio un pujaso");
        }
        actualizarbusqueda();
        lblbusqueda.setVisible(false);
        cmbbusqueda.setVisible(false);
        lblcodigo.setVisible(false);
        txtcod.setVisible(false);
        lblusuario.setVisible(false);
        txtusuario.setVisible(false);
        lblclave.setVisible(false);
        txtclave.setVisible(false);
        lblestado.setVisible(false);
        cmbestado.setVisible(false);
        cmbcodestado.setVisible(false);
        lblempleado.setVisible(false);
        cmbemp.setVisible(false);
        cmbcodemp.setVisible(false);
        btnaccion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblestado = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        lblusuario = new javax.swing.JLabel();
        cmbestado = new javax.swing.JComboBox<>();
        txtcod = new javax.swing.JTextField();
        lblcodigo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmboperacion = new javax.swing.JComboBox<>();
        btnaccion = new javax.swing.JButton();
        cmbbusqueda = new javax.swing.JComboBox<>();
        lblbusqueda = new javax.swing.JLabel();
        lblclave = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();
        lblempleado = new javax.swing.JLabel();
        cmbcodemp = new javax.swing.JComboBox<>();
        cmbemp = new javax.swing.JComboBox<>();
        cmbcodestado = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USUARIOS");
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblestado.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblestado.setText("Estado");
        getContentPane().add(lblestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        txtusuario.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 180, -1));

        lblusuario.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblusuario.setText("Usuario");
        getContentPane().add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        cmbestado.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cmbestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Activo", "Inactivo" }));
        cmbestado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbestadoItemStateChanged(evt);
            }
        });
        cmbestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbestadoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 115, -1));

        txtcod.setEditable(false);
        txtcod.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 84, -1));

        lblcodigo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblcodigo.setText("Código");
        getContentPane().add(lblcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Operación");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        cmboperacion.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cmboperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Agregar", "Modificar", "Eliminar" }));
        cmboperacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmboperacionItemStateChanged(evt);
            }
        });
        cmboperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboperacionActionPerformed(evt);
            }
        });
        getContentPane().add(cmboperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 115, -1));

        btnaccion.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnaccion.setText("jButton1");
        btnaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        cmbbusqueda.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cmbbusqueda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbusquedaItemStateChanged(evt);
            }
        });
        cmbbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 180, -1));

        lblbusqueda.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblbusqueda.setText("Usuario");
        getContentPane().add(lblbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        lblclave.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblclave.setText("Clave");
        getContentPane().add(lblclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        txtclave.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 180, -1));

        lblempleado.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblempleado.setText("Empleado");
        getContentPane().add(lblempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        cmbcodemp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbcodempItemStateChanged(evt);
            }
        });
        cmbcodemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcodempActionPerformed(evt);
            }
        });
        getContentPane().add(cmbcodemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 115, -1));

        cmbemp.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cmbemp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbempItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 180, -1));

        cmbcodestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "0" }));
        cmbcodestado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbcodestadoItemStateChanged(evt);
            }
        });
        cmbcodestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcodestadoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbcodestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 115, -1));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbestadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbestadoItemStateChanged

    }//GEN-LAST:event_cmbestadoItemStateChanged

    private void cmboperacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmboperacionItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboperacionItemStateChanged

    private void cmboperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboperacionActionPerformed
        // TODO add your handling code here:
        if (cmboperacion.getSelectedIndex()==1) {
            limpiar();
            lblbusqueda.setVisible(false);
            cmbbusqueda.setVisible(false);
            lblusuario.setVisible(true);
            txtusuario.setVisible(true);
            lblcodigo.setVisible(false);
            txtcod.setVisible(false);
            lblclave.setVisible(true);
            txtclave.setVisible(true);
            lblestado.setVisible(true);
            cmbestado.setVisible(true);
            lblempleado.setVisible(true);
            cmbemp.setVisible(true);
            btnaccion.setVisible(true);
            btnaccion.setText("Agregar");
        }else if (cmboperacion.getSelectedIndex()==2) {
            limpiar();
            lblbusqueda.setVisible(true);
            cmbbusqueda.setVisible(true);
            lblusuario.setVisible(true);
            txtusuario.setVisible(true);
            lblcodigo.setVisible(true);
            txtcod.setVisible(true);
            lblclave.setVisible(true);
            txtclave.setVisible(true);
            lblestado.setVisible(true);
            cmbestado.setVisible(true);
            lblempleado.setVisible(true);
            cmbemp.setVisible(true);
            btnaccion.setVisible(false);
            btnaccion.setText("Modificar");
        }else if (cmboperacion.getSelectedIndex()==3) {
            limpiar();
            lblbusqueda.setVisible(true);
            cmbbusqueda.setVisible(true);
            lblusuario.setVisible(true);
            txtusuario.setVisible(true);
            lblcodigo.setVisible(true);
            txtcod.setVisible(true);
            lblclave.setVisible(true);
            txtclave.setVisible(true);
            lblestado.setVisible(true);
            cmbestado.setVisible(true);
            lblempleado.setVisible(true);
            cmbemp.setVisible(true);
            btnaccion.setVisible(false);
            btnaccion.setText("Eliminar");
        }else{
            limpiar();
            lblbusqueda.setVisible(false);
            cmbbusqueda.setVisible(false);
            lblcodigo.setVisible(false);
            txtcod.setVisible(false);
            lblusuario.setVisible(false);
            txtusuario.setVisible(false);
            lblclave.setVisible(false);
            txtclave.setVisible(false);
            lblestado.setVisible(false);
            cmbestado.setVisible(false);
            cmbcodestado.setVisible(false);
            lblempleado.setVisible(false);
            cmbemp.setVisible(false);
            cmbcodemp.setVisible(false);
        }
    }//GEN-LAST:event_cmboperacionActionPerformed

    private void btnaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccionActionPerformed
        // TODO add your handling code here:
        if (cmboperacion.getSelectedIndex()==1) {
            if (txtusuario.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Debe de ingresar el nombre de usuario");
            }else if (txtclave.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Debe de ingresar la clave del usuario");
            }else if (cmbestado.getSelectedIndex()==0) {
                JOptionPane.showMessageDialog(this, "Debe de seleccionar el estado del usuario");
            }else if (cmbemp.getSelectedIndex()==0) {
                JOptionPane.showMessageDialog(this, "Debe de seleccionar el empleado al cual le pertenece el usuario");
            }else{
                try{
                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                    PreparedStatement pst = cn.prepareStatement("insert into usuarios values(?,?,?,?,?)");
                    pst.setString(1, String.valueOf(intCod));
                    pst.setString(2, txtusuario.getText().trim());
                    pst.setString(3, txtclave.getText().trim());
                    pst.setString(4, String.valueOf(cmbcodestado.getSelectedItem()));
                    pst.setString(5, String.valueOf(cmbcodemp.getSelectedItem()));
                    pst.executeUpdate();
                    intCod++;
                    JOptionPane.showMessageDialog(this, "Datos ingresados correctamente","ÉXITO",JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                    actualizarbusqueda();
                }catch (Exception e){
                    System.out.println("le dio un error");
                }
            }
        }else if (cmboperacion.getSelectedIndex()==2) {
            if (JOptionPane.showConfirmDialog(this, "Está seguro de modificar los datos?","MODIFICAR",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
                try {
                    String ID = txtcod.getText().trim();

                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                    PreparedStatement pst = cn.prepareStatement("update usuarios set nombre_usuario= ?, clave_usuario= ?, estado_usuario= ?, codigo_emp= ? where codigo_usuario= " + ID);

                    pst.setString(1, txtusuario.getText().trim());
                    pst.setString(2, txtclave.getText().trim());
                    pst.setString(3, cmbcodestado.getSelectedItem().toString());
                    pst.setString(4, cmbcodemp.getSelectedItem().toString());
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Datos modificados correctamente","ÉXITO",JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                    actualizarbusqueda();
                } catch (Exception e) {
                    System.out.println("le dio un pujaso");
                }
            }
        }else if (cmboperacion.getSelectedIndex()==3) {
            if (JOptionPane.showConfirmDialog(this, "Está seguro de eliminar los datos?","MODIFICAR",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
                try {
                    String ID = txtcod.getText().trim();

                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                    PreparedStatement pst = cn.prepareStatement("delete from usuarios where codigo_usuario= " + ID);

                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Datos eliminados correctamente","ÉXITO",JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                    actualizarbusqueda();
                } catch (Exception e) {
                    System.out.println("le dio un pujaso");
                }
            }
        }
    }//GEN-LAST:event_btnaccionActionPerformed

    private void cmbbusquedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbusquedaItemStateChanged
        // TODO add your handling code here:
        if (cmbbusqueda.getSelectedIndex()!=0) {
            try{
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_nomina", "root", "");
                PreparedStatement pst = cn.prepareStatement("select * from usuarios where nombre_usuario = ?");
                pst.setString(1,cmbbusqueda.getSelectedItem().toString());
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    txtcod.setText(rs.getString("codigo_usuario"));
                    txtusuario.setText(rs.getString("nombre_usuario"));
                    txtclave.setText(rs.getString("clave_usuario"));
                    cmbcodestado.setSelectedItem(rs.getString("estado_usuario"));
                    cmbcodemp.setSelectedItem(rs.getString("codigo_emp"));
                    btnaccion.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "No encontrado");
                }

            }catch (Exception e){
                //System.out.println("le dio un pujaso");
            }
        }else{
            limpiar();
            if (cmboperacion.getSelectedIndex()!=1) {
                btnaccion.setVisible(false);
            }
            
        }
    }//GEN-LAST:event_cmbbusquedaItemStateChanged

    private void cmbbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbusquedaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbbusquedaActionPerformed

    private void cmbcodempItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbcodempItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcodempItemStateChanged

    private void cmbcodempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcodempActionPerformed
        // TODO add your handling code here:
        try{
            this.cmbemp.setSelectedIndex(this.cmbcodemp.getSelectedIndex());
        }catch(Exception e){
        }
    }//GEN-LAST:event_cmbcodempActionPerformed

    private void cmbempItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbempItemStateChanged
        // TODO add your handling code here:
        try{
            this.cmbcodemp.setSelectedIndex(this.cmbemp.getSelectedIndex());
        }catch(Exception e){
        }
    }//GEN-LAST:event_cmbempItemStateChanged

    private void cmbcodestadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbcodestadoItemStateChanged
        // TODO add your handling code here:
        try{
            this.cmbemp.setSelectedIndex(this.cmbcodemp.getSelectedIndex());
        }catch(Exception e){
        }
    }//GEN-LAST:event_cmbcodestadoItemStateChanged

    private void cmbcodestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcodestadoActionPerformed
        // TODO add your handling code here:
        try{
            this.cmbestado.setSelectedIndex(this.cmbcodestado.getSelectedIndex());
        }catch(Exception e){
        }
    }//GEN-LAST:event_cmbcodestadoActionPerformed

    private void cmbestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbestadoActionPerformed
        // TODO add your handling code here:
        try{
            this.cmbcodestado.setSelectedIndex(this.cmbestado.getSelectedIndex());
        }catch(Exception e){
        }
    }//GEN-LAST:event_cmbestadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menú inf=new Menú();
        this.dispose();
        inf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaccion;
    private javax.swing.JComboBox<String> cmbbusqueda;
    private javax.swing.JComboBox<String> cmbcodemp;
    private javax.swing.JComboBox<String> cmbcodestado;
    private javax.swing.JComboBox<String> cmbemp;
    private javax.swing.JComboBox<String> cmbestado;
    private javax.swing.JComboBox<String> cmboperacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblbusqueda;
    private javax.swing.JLabel lblclave;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblempleado;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JTextField txtclave;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
