/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package departamentalizacionplanilla;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *Bryan Orlando Aguirre Sagastume
*0901-17-646
*Planilla para calcular el sueldo líquido de trabajadores y obtener los totales devengados por departamento 
 * @author Bryan
 */
public class Planilla extends javax.swing.JFrame {
String strDep[]=new String [6];
String strPlanilla[][]=new String [11][7];
int intRandom;
    /**
     * Creates new form Planilla
     */
    public Planilla() {
        funGenerarPlanilla();
        initComponents();
        //instrucción para mostrar la matriz en la tabla del frame
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            
             strPlanilla,
            new String [] {
                "Nombre", "Sueldo Base", "Total Deducciones", "Total Percepciones", "Sueldo Liquido", "Departamento"
            }
        ));
        
        DefaultTableModel dtmTabla= new DefaultTableModel(new String[] {"Total por departamento"},0);
        for (int i = 0; i < 5; i++) {
            Object[] obTotal={strDep[i]};
            dtmTabla.addRow(obTotal);
        }
        jTable2.setModel(dtmTabla);
        
    }
    public void funGenerarPlanilla(){
        for (int i = 0; i < 5; i++) {
            strDep[i]="0";
        }
        for (int i = 0; i < 10; i++) {
            strPlanilla[i][0]=JOptionPane.showInputDialog("Ingrese el nombre completo de la persona No. "+(i+1));
            intRandom=(int)(Math.random()*7500)+2500;
            strPlanilla[i][1]=String.valueOf(intRandom);
            intRandom=(int)(Math.random()*3500)+1500;
            System.out.println(intRandom);
            strPlanilla[i][2]=String.valueOf(intRandom);
            intRandom=(int)(Math.random()*1500)+1000;
            System.out.println(intRandom);
            strPlanilla[i][3]=String.valueOf(intRandom);
            strPlanilla[i][4]=String.valueOf(Integer.parseInt(strPlanilla[i][1])+Integer.parseInt(strPlanilla[i][3])-Integer.parseInt(strPlanilla[i][2]));
            System.out.println(strPlanilla[i][5]);
            intRandom=(int)(Math.random()*5)+1;
            strPlanilla[i][5]=String.valueOf(intRandom);
            System.out.println(intRandom);
        }
        for (int i = 0; i < 10; i++) {
            if (Integer.parseInt(strPlanilla[i][5])==1) {
                strDep[1]=String.valueOf(Integer.parseInt(strPlanilla[i][4])+Integer.parseInt(strDep[0]));
            }else if (Integer.parseInt(strPlanilla[i][5])==2) {
                strDep[2]=String.valueOf(Integer.parseInt(strPlanilla[i][4])+Integer.parseInt(strDep[1]));
            }else if (Integer.parseInt(strPlanilla[i][5])==3) {
                strDep[3]=String.valueOf(Integer.parseInt(strPlanilla[i][4])+Integer.parseInt(strDep[2]));
            }else if (Integer.parseInt(strPlanilla[i][5])==4) {
                strDep[4]=String.valueOf(Integer.parseInt(strPlanilla[i][4])+Integer.parseInt(strDep[3]));
            }else{
                strDep[5]=String.valueOf(Integer.parseInt(strPlanilla[i][4])+Integer.parseInt(strDep[4]));
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Sueldo Base", "Total Deducciones", "Total Percepciones", "Sueldo Liquido", "Departamento"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Realizar de nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Total Departamento"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jButton1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jButton1)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        funGenerarPlanilla();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
